import { ToolConfig } from './types';

export const TOOL_CATALOG: ToolConfig[] = [
  { category: 'scene', name: 'management', enabled: true, description: 'Current scene, scene list, open/save/create/close scene' },
  { category: 'scene', name: 'hierarchy', enabled: true, description: 'Read scene hierarchy and node tree' },
  { category: 'scene', name: 'execution_control', enabled: true, description: 'Invoke scene script helpers and utility actions' },
  { category: 'node', name: 'query', enabled: true, description: 'Find nodes and inspect node details' },
  { category: 'node', name: 'lifecycle', enabled: true, description: 'Create/delete/duplicate/move nodes' },
  { category: 'node', name: 'transform', enabled: true, description: 'Set node transform and basic properties' },
  { category: 'component', name: 'manage', enabled: true, description: 'Add/remove components on nodes' },
  { category: 'component', name: 'query', enabled: true, description: 'Inspect component data and available types' },
  { category: 'component', name: 'property', enabled: true, description: 'Set component properties' },
  { category: 'component', name: 'resource', enabled: true, description: 'Assign strongly-typed resource references such as SpriteFrame assets' },
  { category: 'component', name: 'script', enabled: true, description: 'Attach script components by asset or class name' },
  { category: 'prefab', name: 'browse', enabled: true, description: 'List prefab assets and inspect prefab info' },
  { category: 'prefab', name: 'lifecycle', enabled: true, description: 'Create, duplicate and delete prefab assets' },
  { category: 'prefab', name: 'instance', enabled: true, description: 'Instantiate prefab into active scene' },
  { category: 'project', name: 'manage', enabled: true, description: 'Get project info and editor/project settings' },
  { category: 'project', name: 'build_system', enabled: true, description: 'Open build panel and expose build-related hints' },
  { category: 'project', name: 'asset_query', enabled: true, description: 'Query project assets by name/type/path' },
  { category: 'project', name: 'asset_operations', enabled: true, description: 'Create/copy/move/delete/import asset files' },
  { category: 'project', name: 'asset_analyze', enabled: true, description: 'Inspect asset details and dependency-related metadata' },
  { category: 'script', name: 'file', enabled: true, description: 'Read/create/update/delete script assets and refresh asset db' },
  { category: 'script', name: 'workflow', enabled: true, description: 'Create/update scripts and attach them to scene nodes' },
  { category: 'workflow', name: 'plan', enabled: true, description: 'Apply or dry-run a batch action plan derived from Figma/YAML' },
  { category: 'workflow', name: 'scene_apply', enabled: true, description: 'Apply a safer scene workflow with refresh/reload/save controls' },
  { category: 'workflow', name: 'scene_bind', enabled: true, description: 'Bind scene resource references through editor APIs and optionally save' },
  { category: 'debug', name: 'console', enabled: true, description: 'Execute debug script and inspect lightweight diagnostics' },
  { category: 'debug', name: 'logs', enabled: true, description: 'Read editor/project log files' },
  { category: 'preferences', name: 'manage', enabled: true, description: 'Get/set extension preferences stored in project settings' },
  { category: 'server', name: 'info', enabled: true, description: 'Query MCP server runtime and local network information' },
  { category: 'broadcast', name: 'message', enabled: true, description: 'Broadcast log and lightweight event tracking' },
  { category: 'validation', name: 'helpers', enabled: true, description: 'Validate JSON params and format MCP requests' },
];
